### ISSUE TITLE
sintesis

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Rosa218#1]
[Sintesis_ Calidad de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Rosa218/files/9601090/Sintesis_.Calidad.de.software.pdf)

**Comment by Lizzetee** [comment]
Calificación: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
